# -*- coding: utf-8 -*-
"""PanSharpening_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6NzQr5n_H5IBnouOE1kMKxqP0GHgNh9
"""

import numpy as np
import rasterio

with rasterio.open("nir_highres.tif") as src_nir:
    nir = src_nir.read(1)

with rasterio.open("rgb_resampled.tif") as src_rgb:
    red = src_rgb.read(1)
    green = src_rgb.read(2)
    blue = src_rgb.read(3)

intensity = (red + green + blue) / 3.0

intensity[intensity == 0] = 0.00001

ratio = nir / intensity

red_sharpened = (red * ratio).astype(np.uint16)
green_sharpened = (green * ratio).astype(np.uint16)
blue_sharpened = (blue * ratio).astype(np.uint16)

